name: EnjinCraft
description: EnjinCraft spigot implementation, a platform for game assets on the Ethereum blockchain.
version: @version@-spigot
authors: [Evan "Favorlock" Lindsay, Damien Gallagher, Tobias Drewry, Enjin Team]
website: https://enjin.io
main: com.enjin.enjincraft.spigot.EnjPlugin
softdepend: [Vault, PlaceholderAPI]
api-version: 1.13
commands:
  enj:
    description: Reference command for EnjinCraft.
permissions:
  enjincraft.*:
    default: op
    children:
      enjincraft.player: true
      enjincraft.conf: true
  enjincraft.conf:
    default: false
    children:
      enjincraft.conf.set: true
      enjincraft.conf.reload: true
  enjincraft.player:
    default: true
    children:
      enjincraft.root: true
      enjincraft.balance: true
      enjincraft.help: true
      enjincraft.link: true
      enjincraft.send: true
      enjincraft.trade: true
      enjincraft.unlink: true
      enjincraft.wallet: true
  enjincraft.trade:
    children:
      enjincraft.trade.invite: true
      enjincraft.trade.accept: true
      enjincraft.trade.decline: true