name: Enjin_Coin_Spigot_Plugin
description: Spigot plugin for the Enjin Coin Minecraft Framework, a platform for game assets on the Ethereum block-chain.
version: @version@-spigot
authors: [Evan "Favorlock" Lindsay, Damien Gallagher, Tobias Drewry, Enjin Coin Team]
website: https://enjincoin.io
main: com.enjin.enjincoin.spigot_plugin.Main
softdepend: [Vault]
api-version: 1.13
commands:
  enj:
    description: Enjin Coin root command.
    usage: /<command> <subcommand> [args]
  enj balance:
    description: Display wallet address and Ethereum and Enjin Coin balances as well as a list of owned CrytoItems.
    usage: /<command> <subcommand> [args]
  enj link:
    description: Display linking code or linked address if available.
    usage: /<command> <subcommand> [args]
  enj wallet:
    description: Opens a wallet inventory panel which allows for checkout of owned CrytoItems.
    usage: /<command> <subcommand> [args]