name: ECMP
description: Spigot plugin for the Enjin Coin Minecraft Framework, a platform for game assets on the Ethereum block-chain.
version: @version@-spigot
authors: [Evan "Favorlock" Lindsay, Damien Gallagher, Tobias Drewry, Enjin Coin Team]
website: https://enjincoin.io
main: com.enjin.enjincoin.spigot_plugin.Main
softdepend: [Vault]
api-version: 1.13
commands:
  enj:
    description: Enjin Coin root command.
    usage: /<command>
    permission: enjincoin
  enj balance:
    description: Display wallet address and Ethereum and Enjin Coin balances as well as a list of balance CrytoItems.
    usage: /<command> balance
    permission: enjincoin.balance
  enj link:
    description: Display linking code or linked address if available.
    usage: /<command> link
    permission: enjincoin.link
  enj unlink:
    description: Unlink the wallet from your account.
    usage: /<command> unlink
  enj wallet:
    description: Opens a wallet inventory panel which allows for checkout of balance CrytoItems.
    usage: /<command> wallet
    permission: enjincoin.wallet
  enj trade:
    description: Trade tokens with another player.
    usage: /<command> trade invite <player>
    permission: enjincoin.trade
  enj send:
    description: Send a token to another player.
    usage: /<command> send <player>
    permission: enjincoin.send
permissions:
  enjincoin.*:
    description: Gives access to all ECMP commands
    children:
      enjincoin.balance
      enjincoin.link
      enjincoin.unlink
      enjincoin.wallet
      enjincoin.trade
      enjincoin.send
    enjincoin.balance:
      default: true
    enjincoin.link:
      default: true
    enjincoin.unlink:
      default: true
    enjincoin.wallet:
      default: true
    enjincoin.trade:
      default: false
    enjincoin.send:
      default: false